[BE] 카테고리 관련 기능
todolist-team2/todo-max pull request #11
Opened 2023-07-13 08:34 UTC by HyowonSin

## 관련 이슈
- #2 #7 #8

## 의도 
카테고리 비즈니스 로직 구현
- 카테고리 등록, 수정, 삭제

## 구체적으로 봐야하는 포인트, 세부적인 변경점
- 카테고리가 `category` 테이블에 잘 저장되는지
- 아이디가 잘 생성되는지
&nbsp;
- 카테고리가 잘 수정되는지
&nbsp;
- 카테고리가 잘 삭제되는지
- 카테고리가 삭제될 때, 해당 카드들이 모두 삭제되는지
&nbsp;
- 리퀘스트에서 빈 값을 보내면 에러 메세지 보내게 하였습니다.

## 추신
- 브랜치가 좀 섞여서 한번에 보내게 되었습니다.. ㅠ
- 예외 처리가 필요한 부분들 같이 체크해주시면 감사하겠습니다.
- 포스트맨으로 API 테스트는 진행했고 테스트 코드는 내일 추가할 예정입니다.

related to #2 #7 #8

2023-07-13 09:17 UTC, AlbertImKr approved these changes
수고하셨습니다 👍

2023-07-13 09:17 UTC, AlbertImKr commented on backend/build.gradle
> +    runtimeOnly 'com.h2database:h2'
h2 사용이유가 있을까요 ?

2023-07-13 09:17 UTC, AlbertImKr commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
spring validation 👍

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +		return ResponseEntity.status(HttpStatus.CREATED).body(categoryService.saveCategory(categoryRequestDto));
controller 메서드 이름과 일치하는 `categoryService.create()` or` categoryService.createCategory()`가   더 좋을 것 같아요.
save는 Repository에 사용하는 네이밍 같아요.

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +		return ResponseEntity.ok(categoryService.modifyCategory(categoryId, categoryRequestDto));
Controller 메서드 이름과 service 메서드 이름이 일치하면 더 좋을 것 같아요

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +		categoryService.removeCategory(categoryId);
Controller 메서드 이름과 service 메서드 이름이 일치하면 더 좋을 것 같아요

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/exeption/GlobalExceptionHandler.java
> +				.body(new ErrorResponse(ErrorCode.VALIDATION_FAILED, message));
Validation Exception 구현하셨네요. 👍

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
> +		return categoryId;
변경되지 않는 categoryId이여서 받고 return할 필요 없어 보여요.

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
> +			statement.executeUpdate();
NamedParameterJdbcTemplate 사용하면 간소화 할 수 있을 것 같아요.

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
> +			statement.executeUpdate();
NamedParameterJdbcTemplate 사용하면 간소화 할 수 있을 것 같아요.

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/service/CategoryService.java
> +	// TODO: 카테고리도 활동 기록에 저장해야 하는지?
저장해야 할 것 같아요. 나중에 AOP로 구현 하면 될 것 같아요.

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/java/kr/codesquad/todo/service/CategoryService.java
> +		cardRepository.deleteAllByCategoryId(categoryId);
논의 할 주제 인것 같아요

2023-07-13 09:17 UTC, AlbertImKr commented on backend/src/main/resources/application-h2.yml
> +      enabled: true
h2 필요 없을 것 같아요.

2023-07-13 09:59 UTC, 23Yong requested changes
전체적으로 메서드 사이에 두 라인이 들어간 것 같아요! 나머지는 수정해 주세용~

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +
한 줄이 더 들어갔네요! 코드 컨벤션 지켜주세용

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +	public ResponseEntity<?> updateCategory(@PathVariable Long categoryId, @RequestBody CategoryRequestDto categoryRequestDto) {
`?` 와일드 카드 타입을 사용할 때는 한정적 와일드 카드 타입을 사용하는 것이 좋습니다!
`?`를 사용하게 되면 `ResponseEntity<Object>`와 다름이 없어지기 때문입니다. 그래서 `ResponseEntity<? extends ~>`나 `ResponseEntity<? super ~>` 정도로 사용합니다.

그런데 여기서는 `categoryService.modifyCategory` 메서드가 `Long`을 반환하고 있기 떄문에 다음과 같이 API 명세에 맞추어 반환하면 좋을 것 같습니다.
```java
public ResponseEntity<Map<String, Long>> updateCategory(~~) {
    return ResponseEntity.ok(Map.of("categoryId", categoryService.modifyCategory(~~));
}
```

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +	public ResponseEntity<?> deleteCategory(@PathVariable Long categoryId) {
여기도 `ResponseEntity<Void>` 이면 될 것 같습니다!

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/dto/request/CategoryRequestDto.java
> +public class CategoryRequestDto {
이전에 `dto`키워드를 붙이지 않고 클래스 네이밍을 했기 때문에 어색한 것 같습니다.
맞춰주시면 감사하겠습니다!

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/dto/request/CategoryRequestDto.java
> +
여기도 코드 컨벤션을 지켜주세요!
7라인 이후 빈 라인 한 줄, 11라인은 지워주세요!

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/domain/Category.java
> +	}
필드 - 생성자 -getter 순서로 맞춰주면 좋을 것 같아요ㅎㅎ

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
> +
여기도 코드 컨벤션을 지켜주세요ㅎㅎ

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
> +	private final DataSource dataSource;
Albert 말대로 `NamedParameterJdbcTemplate`을 사용하면 `datasource`는 필드로 둘 필요가 없어 보입니다!

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
> +
이곳도 코드 컨벤션을 지켜주세요! 32라인도 마찬가지 입니다ㅎㅎ

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/service/CategoryService.java
> +	public Long saveCategory(CategoryRequestDto categoryRequestDto) {
여기에는 `@Transactional` 이 달려있지 않네요!

2023-07-13 09:59 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +	public ResponseEntity<?> createCategory(@Valid @RequestBody CategoryRequestDto categoryRequestDto) {
여기도 `ResponseEntity<Map<String, Long>>` 정도로 바꾸면 될 것 같습니다!

2023-07-14 01:59 UTC, Jeongwisdom approved these changes

2023-07-14 02:00 UTC, merged

2023-07-17 05:05 UTC, HyowonSin commented on backend/build.gradle
> +    runtimeOnly 'com.h2database:h2'
제가 도커를 안 깔아서 테스트 용으로 썼었습니다..!
이건 뺄게용

2023-07-17 05:05 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +
죄송합니다 플러그인 깔린 것 중에 어떤 넘이 2줄씩 비웠네용
수정하겠습니다!

2023-07-17 05:05 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +		return ResponseEntity.status(HttpStatus.CREATED).body(categoryService.saveCategory(categoryRequestDto));
오호.. 저는 컨트롤러랑 서비스 메서드가 겹쳐서 
일부러 헷갈릴까봐 이렇게 바꿨었는데
이게 더 헷갈렸던 것 같네요
통일해보겠습니다!

2023-07-17 05:05 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/todo/dto/request/CategoryRequestDto.java
> +public class CategoryRequestDto {
넵 알겠습니다!

2023-07-17 06:30 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/todo/controller/CategoryController.java
> +	public ResponseEntity<?> updateCategory(@PathVariable Long categoryId, @RequestBody CategoryRequestDto categoryRequestDto) {
조언 감사드립니다!
제가 좀 잘 못 알고 있던 것 같아서
브루니가 말씀해주신 부분 조금 더 찾아봤습니다 ㅋㅋ

저희 상황에는 이미 API 명세도 정해져 있고, 여러 타입을 고려할 필요도 없어서
지정된 타입을 명시하는 것이 유지보수 측면이든 안정성이든 당연히 좋고

와일드카드는 와일드카드가 필요할 때 써야 하는군요
정말로 객체 타입이 명확하지 않은 경우나 여러 가지 응답을 받아야 하거나..